"""adicionando nome de cidade 

Revision ID: 764fed63e8f3
Revises: 7129630a530a
Create Date: 2025-12-20 14:56:53.016229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764fed63e8f3'
down_revision: Union[str, Sequence[str], None] = '7129630a530a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cidade',
    sa.Column('id_cidade', sa.Integer(), nullable=False),
    sa.Column('cidade_nome', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('log', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_cidade')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Cidade')
    # ### end Alembic commands ###
