"""adicionandondo Clima

Revision ID: 80f87be349fd
Revises: daae8edbf119
Create Date: 2025-12-27 15:14:20.280156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f87be349fd'
down_revision: Union[str, Sequence[str], None] = 'daae8edbf119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clima',
    sa.Column('id_clima', sa.Integer(), nullable=False),
    sa.Column('id_cidade', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_cidade'], ['Cidade.id_cidade'], ),
    sa.PrimaryKeyConstraint('id_clima')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Clima')
    # ### end Alembic commands ###
