"""Description of changes

Revision ID: 83acf371b96d
Revises: 764fed63e8f3
Create Date: 2025-12-20 15:27:38.270791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83acf371b96d'
down_revision: Union[str, Sequence[str], None] = '764fed63e8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cidade', sa.Column('long', sa.Float(), nullable=False))
    op.drop_column('Cidade', 'log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cidade', sa.Column('log', sa.FLOAT(), nullable=False))
    op.drop_column('Cidade', 'long')
    # ### end Alembic commands ###
