"""remodelando o banco de dados

Revision ID: aa9d97e3d892
Revises: 83acf371b96d
Create Date: 2025-12-21 14:20:37.899270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9d97e3d892'
down_revision: Union[str, Sequence[str], None] = '83acf371b96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    with op.batch_alter_table("Cidade") as batch_op:
       op.drop_table("Cidade")
       op.create_table(
        "Cidade",
        sa.Column("id_cidade", sa.Integer(), primary_key=True),
        sa.Column("cidade_nome", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("long", sa.Float(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_cidade_user"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cidade', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'Cidade', type_='foreignkey')
    op.drop_column('Cidade', 'user_id')
    # ### end Alembic commands ###
