"""description of changes

Revision ID: daae8edbf119
Revises: aa9d97e3d892
Create Date: 2025-12-21 14:57:07.352583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daae8edbf119'
down_revision: Union[str, Sequence[str], None] = 'aa9d97e3d892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cidade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cidade', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
