# Generated by Django 5.2.7 on 2025-10-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contact_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emails',
            new_name='email',
        ),
    ]
